## Deliverable 3. Create a Travel Itinerary Map.

In [4]:
# Dependencies and Setup
import pandas as pd
import requests
import gmaps
import os

# Import API key
from config import g_key

# Configure gmaps
gmaps.configure(api_key=g_key)

In [5]:
# 1. Read the WeatherPy_vacation.csv into a DataFrame.
vacation_df = pd.read_csv(os.path.join("..","Vacation_Search","WeatherPy_vacation.csv"))
vacation_df.head()

City_ID     City Country  Max Temp Current Description      Lat       Lng  \
0        7   Atuona      PF     78.31          light rain  -9.8000 -139.0333   
1        8    Kapaa      US     82.38           clear sky  22.0752 -159.3190   
2       17  Sharjah      AE     75.18                dust  25.3573   55.4033   
3       19    Vaini      TO     75.36       broken clouds -21.2000 -175.2000   
4       22  Itarema      BR     77.95       broken clouds  -2.9248  -39.9167   

                            Hotel Name  
0                          Villa Enata  
1  Sheraton Kauai Coconut Beach Resort  
2               Swiss Belhotel Sharjah  
3                  Keleti Beach Resort  
4   Sea Lounge! Bar, Club & Restaurant

In [7]:
# 2. Using the template add the city name, the country code, the weather description and maximum temperature for the city.
info_box_template = """
<dl>
<dt>City</dt><dd>{City}</dd>
<dt>Country</dt><dd>{Country}</dd>
<dt>Weather Description</dt><dd>{Current Description}</dd>
<dt>Max Temp</dt><dd>{Max Temp} °F</dd>
</dl>
"""

# 3a. Get the data from each row and add it to the formatting template and store the data in a list.
hotel_info = [info_box_template.format(**row) for index, row in vacation_df.iterrows()]

# 3b. Get the latitude and longitude from each row and store in a new DataFrame.
locations = vacation_df[["Lat", "Lng"]]

In [8]:
# 4a. Add a marker layer for each city to the map.
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
markers = gmaps.marker_layer(locations, info_box_content=hotel_info)
fig.add_layer(markers)
# 4b. Display the figure
fig

Figure(layout=FigureLayout(height='420px'))

In [17]:
# From the map above pick 4 cities and create a vacation itinerary route to travel between the four cities. 
vacation_start = "Meadow Lake"
vacation_end = "Meadow Lake"
city2 = "Tucumcari"
city3 = "Rancho Palos Verdes"
city4 = "Lompoc" 

# 5. Create DataFrames for the starting and ending city by filtering the 'vacation_df' using the loc method
vacation_start = vacation_df.loc[vacation_df["City"] == vacation_start]
vacation_end = vacation_df.loc[vacation_df["City"] == vacation_end] 
vacation_start

City_ID         City Country  Max Temp Current Description      Lat  \
27      124  Meadow Lake      US     75.47           clear sky  34.8014   

         Lng          Hotel Name  
27 -106.5436  TumbleWeed RV Park

In [18]:
# 5. Create DataFrames for 2 city by filtering the 'vacation_df' using the loc method

vacation_stop2 = vacation_df.loc[vacation_df["City"] == city2]
vacation_stop2

City_ID       City Country  Max Temp Current Description      Lat  \
141      561  Tucumcari      US     75.04           clear sky  35.1717   

         Lng                                         Hotel Name  
141 -103.725  Holiday Inn Express & Suites Tucumcari, an IHG...

In [19]:
# 5. Create DataFrames for 3 city by filtering the 'vacation_df' using the loc method
vacation_stop3 = vacation_df.loc[vacation_df["City"] == city3] 
vacation_stop3

City_ID                 City Country  Max Temp Current Description  \
137      548  Rancho Palos Verdes      US     84.27       broken clouds   

         Lat      Lng       Hotel Name  
137  33.7445 -118.387  Terranea Resort

In [20]:
# 5. Create DataFrames for 4 city by filtering the 'vacation_df' using the loc method
vacation_stop4 = vacation_df.loc[vacation_df["City"] == city4] 
vacation_stop4

City_ID    City Country  Max Temp Current Description      Lat       Lng  \
109      434  Lompoc      US     75.78          few clouds  34.6391 -120.4579   

                                   Hotel Name  
109  Holiday Inn Express Lompoc, an IHG Hotel

In [29]:
# 6. Get the latitude-longitude pairs as tuples from each city DataFrame using the to_numpy function and list indexing.
start = vacation_start[["Lat", "Lng"]].to_numpy()[0]
end = vacation_end[["Lat", "Lng"]].to_numpy()[0]
stop1 = vacation_stop2[["Lat", "Lng"]].to_numpy()[0]
stop2 = vacation_stop3[["Lat", "Lng"]].to_numpy()[0]
stop3 = vacation_stop4[["Lat", "Lng"]].to_numpy()[0]  
start, end, stop1, stop2, stop3

(array([  34.8014, -106.5436]),
 array([  34.8014, -106.5436]),
 array([  35.1717, -103.725 ]),
 array([  33.7445, -118.387 ]),
 array([  34.6391, -120.4579]))

In [11]:
# 7. Create a direction layer map using the start and end latitude-longitude pairs,
# and stop1, stop2, and stop3 as the waypoints. The travel_mode should be "DRIVING", "BICYCLING", or "WALKING".

fig = gmaps.figure()
travel_route = gmaps.directions_layer(start, end, waypoints=[stop1,stop2,stop3], travel_mode="DRIVING" or "BICYCLING" or "WALKING")
fig.add_layer(travel_route)
fig 

Figure(layout=FigureLayout(height='420px'))

In [12]:
# 8. To create a marker layer map between the four cities.
#  Combine the four city DataFrames into one DataFrame using the concat() function.
itinerary_df = pd.concat([vacation_start, vacation_stop2, vacation_stop3, vacation_stop4],ignore_index=True)
itinerary_df 

City_ID                 City Country  Max Temp Current Description  \
0      124          Meadow Lake      US     75.47           clear sky   
1      561            Tucumcari      US     75.04           clear sky   
2      548  Rancho Palos Verdes      US     84.27       broken clouds   
3      434               Lompoc      US     75.78          few clouds   

       Lat       Lng                                         Hotel Name  
0  34.8014 -106.5436                                 TumbleWeed RV Park  
1  35.1717 -103.7250  Holiday Inn Express & Suites Tucumcari, an IHG...  
2  33.7445 -118.3870                                    Terranea Resort  
3  34.6391 -120.4579           Holiday Inn Express Lompoc, an IHG Hotel

In [13]:
# 9 Using the template add city name, the country code, the weather description and maximum temperature for the city. 
info_box_template = """
<dl>
<dt>City</dt><dd>{City}</dd>
<dt>Country</dt><dd>{Country}</dd>
<dt>Weather Description</dt><dd>{Current Description}</dd>
<dt>Max Temp</dt><dd>{Max Temp}</dd>
</dl>
"""

# 10a Get the data from each row and add it to the formatting template and store the data in a list.
hotel_info = [info_box_template.format(**row) for index, row in itinerary_df.iterrows()]

# 10b. Get the latitude and longitude from each row and store in a new DataFrame.
locations = itinerary_df[["Lat", "Lng"]]

In [14]:
# 11a. Add a marker layer for each city to the map.

fig = gmaps.figure()
markers = gmaps.marker_layer(locations, info_box_content=hotel_info)
fig.add_layer(markers)
# 11b. Display the figure
fig 


Figure(layout=FigureLayout(height='420px'))